name: vamr_project_venv
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2024.11.26
  - expat=2.6.4
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - ncurses=6.4
  - openssl=3.0.15
  - pip=24.2
  - python=3.12.8
  - readline=8.2
  - setuptools=75.1.0
  - sqlite=3.45.3
  - tk=8.6.14
  - tzdata=2024b
  - wheel=0.44.0
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
    - contourpy==1.3.1
    - cycler==0.12.1
    - fonttools==4.55.3
    - future==1.0.0
    - jinja2==3.1.5
    - kiwisolver==1.4.8
    - markupsafe==3.0.2
    - matplotlib==3.10.0
    - packaging==24.2
    - pillow==11.0.0
    - pyparsing==3.2.0
    - python-dateutil==2.9.0.post0
    - pyyaml==6.0.2
    - scipy==1.15.0
    - six==1.17.0
    - typeguard==4.4.1
